=== GregGGregGreG/gflogger/src/gflogger/config/xml/gflogger.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns="http://bitbucket.org/vladimir.dolzhenko/gflogger"
		   targetNamespace="http://bitbucket.org/vladimir.dolzhenko/gflogger"
		   elementFormDefault="qualified"
		   attributeFormDefault="unqualified">

	<xs:element name="configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="appender-factory" type="appender-factoryType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="logger-service" type="logger-serviceType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="logger-view" type="logger-viewType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="logger-view-root" type="logger-view-rootType" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="appender-factoryType">
		<xs:sequence>
			<xs:element name="layout" type="layoutType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="class" type="xs:string" use="required"/>
		<xs:attribute name="logLevel" type="log-level" use="required"/>
		<xs:attribute name="append" type="xs:boolean" use="optional"/>
		<xs:attribute name="immediateFlush" type="xs:boolean" use="optional"/>
		<xs:attribute name="datePattern" type="xs:string" use="optional"/>
		<xs:attribute name="fileName" type="xs:string" use="optional"/>
	</xs:complexType>

	<xs:complexType name="layoutType">
		<xs:sequence/>
		<xs:attribute name="class" type="xs:string" use="required"/>
		<xs:attribute name="pattern" type="xs:string" use="required"/>
		<xs:attribute name="timeZoneId" type="xs:string" use="optional"/>
		<xs:attribute name="language" type="xs:string" use="optional"/>
	</xs:complexType>
	
	<xs:simpleType name="log-level">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TRACE"/>
			<xs:enumeration value="DEBUG"/>
			<xs:enumeration value="INFO"/>
			<xs:enumeration value="WARN"/>
			<xs:enumeration value="ERROR"/>
			<xs:enumeration value="FATAL"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="logger-serviceType">
		<xs:sequence>
			<xs:element name="object-formatter" type="object-formatterType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="appender-ref" type="appender-refType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="count" type="xs:integer" use="required"/>
		<xs:attribute name="maxMessageSize" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:complexType name="object-formatterType">
		<xs:attribute name="class" type="xs:string" use="required"/>
		<xs:attribute name="formatter" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="appender-refType">
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="logger-viewType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="service-ref" type="xs:string" use="required"/>
		<xs:attribute name="logLevel" type="log-level" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="logger-view-rootType">
		<xs:attribute name="service-ref" type="xs:string" use="required"/>
		<xs:attribute name="logLevel" type="log-level" use="required"/>
	</xs:complexType>
	
</xs:schema>

=== GregGGregGreG/gflogger/perftest/gflogger.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration 
	xmlns="http://bitbucket.org/vladimir.dolzhenko/gflogger"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://bitbucket.org/vladimir.dolzhenko/gflogger 
		https://bitbucket.org/vladimir.dolzhenko/gflogger/raw/0.0.9.6/src/gflogger.xsd">

	<appender-factory name="consoleAppenderFactory" class="gflogger.appender.ConsoleAppenderFactory"
		logLevel="INFO">
		<layout class="gflogger.PatternLayout"
			pattern="%d{MMM d HH:mm:ss,SSS zzz} %p - %m [%c{2}] [%t]%n"
			timeZoneId="${TZ}"
			language="EN"/>
	</appender-factory>

	<appender-factory name="dailyRollingFileAppenderFactory" class="gflogger.appender.DailyRollingFileAppenderFactory"
		fileName="${logs}/${app}.log"
		logLevel="INFO">
		<layout class="gflogger.PatternLayout"
			pattern="%d{MMM d HH:mm:ss,SSS zzz} %p - %m [%c{2}] [%t]%n"
			timeZoneId="${TZ}"
			language="EN"/>
	</appender-factory>

	  
	<logger-service name="defaultLoggerService" 
		class="gflogger.config.xml.DLoggerServiceFactory" 
		count="1024" maxMessageSize="4096">
		<object-formatter 
			class="perftest.SomeObject"
			formatter="perftest.SomeObjectFormatter"/>
		
		<appender-ref name="consoleAppenderFactory"/>
		<appender-ref name="dailyRollingFileAppenderFactory"/>
	</logger-service>
	
	<logger-view name="com.db" 
		service-ref="defaultLoggerService" logLevel="INFO"/>
		
	<logger-view-root 
		service-ref="defaultLoggerService" logLevel="ERROR"/>

</configuration>
